language: generic
services:
  - docker

env:
  global:
    - ADDITIONAL_DEBS='software-properties-common wget'
    - BEFORE_SCRIPT='sh .ci/install-dependencies.sh'
    - AFTER_SCRIPT='sh .ci/run-tests.sh'
    - NOT_TEST_BUILD=true
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
